#!/usr/bin/env bash

MONO=$(which mono)
BOOGIE="/boogie/Binaries/Boogie.exe"

if [[ ! -x "$MONO" ]]; then
    echo "Error: Boogie requires Mono to run on non-Windows systems."
    exit 1
fi

if [[ ! -e "$BOOGIE" ]]; then
    echo "Error: Boogie.exe not found at $BOOGIE."
    exit 1
fi

"$MONO" "$BOOGIE" "$@"
